/**
 * Frozen codegen path (plan §16.1): committed JSON Schemas → dashboard TypeScript
 * types. Run from apps/dashboard: `npm run gen:types`. One module per schema so
 * types never collide across contract families; `src/generated/` is produced by
 * this script alone — no hand-written client schema exists anywhere.
 */
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { compile } from "json-schema-to-typescript";

const schemasDir = new URL("../../contracts/schemas/", import.meta.url);
const outDir = new URL("../src/generated/", import.meta.url);

const BANNER =
  "/* GENERATED by scripts/gen-types.mjs from apps/contracts/schemas — do not edit. " +
  "Run `npm run gen:types` after any contract change. */\n";

const files = (await readdir(schemasDir))
  .filter((name) => name.endsWith(".json"))
  .sort();
if (files.length === 0) {
  throw new Error(`no JSON schemas found in ${schemasDir.pathname}`);
}

await mkdir(outDir, { recursive: true });
const indexLines = [];
for (const file of files) {
  const schema = JSON.parse(await readFile(new URL(file, schemasDir), "utf8"));
  const stem = file.replace(/\.json$/, "");
  const name = stem.includes(".") ? (stem.split(".").pop() ?? stem) : stem;
  const moduleName = stem.replace(/[^A-Za-z0-9]/g, "_");
  const output = await compile(schema, name, {
    bannerComment: "",
    additionalProperties: false,
    style: { semi: true, singleQuote: false },
  });
  await writeFile(new URL(`${moduleName}.ts`, outDir), `${BANNER}\n${output.trim()}\n`);
  // Only the root type is re-exported: json-schema-to-typescript also emits
  // per-property helper aliases (e.g. CandidateId, RunId) inside every module,
  // and `export *` across them collides. Root names are unique per schema.
  indexLines.push(`export type { ${name} } from "./${moduleName}";`);
}
await writeFile(new URL("index.ts", outDir), `${BANNER}\n${indexLines.join("\n")}\n`);

console.log(`gen:types: ${files.length} schema(s) -> src/generated/ (${files.length} modules + index.ts)`);
